services:
  migrator:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: migrator
    restart: no
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL:?}
      - DATABASE_SCHEMA=dev-factory-hub
  api:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: api
    expose:
      - '5000'
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=${DATABASE_URL:?}
      - CORS_ORIGIN=${CORS_ORIGIN:?}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY:?}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY:?}
      - S3_ENDPOINT=${S3_ENDPOINT:?}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID:?}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY:?}
      - S3_FORCE_PATH_STYLE=false
      - S3_REGION=auto
      - S3_COLLECTIONS_BUCKET_NAME=${S3_COLLECTIONS_BUCKET_NAME:?}
      - S3_TRANSACTIONS_BUCKET_NAME=${S3_TRANSACTIONS_BUCKET_NAME:?}
      - S3_MONEY_EXCHANGES_BUCKET_NAME=${S3_MONEY_EXCHANGES_BUCKET_NAME:?}
      - S3_PAYROLL_PAYMENTS_BUCKET_NAME=${S3_PAYROLL_PAYMENTS_BUCKET_NAME:?}
      - S3_PROFORMA_BUCKET_NAME=${S3_PROFORMA_BUCKET_NAME:?}
      - S3_INVOICES_BUCKET_NAME=${S3_INVOICES_BUCKET_NAME:?}
      - COMPANY_NAME=${COMPANY_NAME:?}
      - COMPANY_ADDRESS=${COMPANY_ADDRESS:?}
      - COMPANY_STATE=${COMPANY_STATE:?}
      - COMPANY_COUNTRY=${COMPANY_COUNTRY:?}
      - COMPANY_LOGO_KEY=${COMPANY_LOGO_KEY:?}
      - DATABASE_SCHEMA=dev-factory-hub
      - POSTMARK_API_KEY=${POSTMARK_API_KEY:?}
      - POSTMARK_TEMPLATE_ALIAS=${POSTMARK_TEMPLATE_ALIAS:?}
      - POSTMARK_YEARLY_TEMPLATE_ALIAS=${POSTMARK_YEARLY_TEMPLATE_ALIAS:?}
      - API_KEY=${API_KEY:?}
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:5000/live',
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    depends_on:
      migrator:
        condition: service_completed_successfully
